footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: front_realsense back_realsense
    front_realsense: {data_type: PointCloud2, clearing: true, marking: true, topic: front/realsense/camera/depth_registered/points, inf_is_valid: true, min_obstacle_height: 0.1}
    back_realsense: {data_type: PointCloud2, clearing: true, marking: true, topic: back/realsense/camera/depth_registered/points, inf_is_valid: true, min_obstacle_height: 0.1}

inflation:
    inflation_radius: 1.0
